# Generated by Django 6.0.4 on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("source_type", models.CharField(choices=[("file", "File"), ("database", "Database"), ("api", "API"), ("url", "URL"), ("manual", "Manual"), ("other", "Other")], default="file", max_length=20)),
                ("data_format", models.CharField(choices=[("text", "Text"), ("image", "Image"), ("csv", "CSV"), ("json", "JSON"), ("other", "Other")], default="text", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("contains_personal_data", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="data_sources", to="projects.project")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="datasource",
            constraint=models.UniqueConstraint(fields=("project", "name"), name="uniq_ds_name_per_project"),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["project", "source_type"], name="ds_project_type_idx"),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(fields=["project", "data_format"], name="ds_project_format_idx"),
        ),
    ]
