# Generated by Django 6.0.5 on 2026-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='data_format',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='text', max_length=20),
        ),
    ]
