# Generated by Django 6.0.5 on 2026-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_alter_datasource_data_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='compliance_violations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
